// tests/n8n/lushaRequestContract.test.mjs
//
// Pins the REAL Lusha v2/person request contract (confirmed live against portal
// 22617666, 2026-07-28): POST body must be {"contacts":[{"contactId",...}]} (an array,
// each element requiring a caller-chosen contactId), with ONLY `email`/`linkedinUrl`
// accepted as identity properties inside an element -- everything else (firstName,
// lastName, companyName, companyDomain, domain, phoneNumber, jobTitle) is REJECTED and
// caused a live 400 "property email should not exist" when the bare identity_keys
// object was posted directly.
//
// Executes the "Lusha Enrich" node's REAL committed jsonBody n8n-expression string via
// `new Function` -- the same idiom tests/n8n/bareEventChainFlow.test.mjs already uses
// to run committed jsCode -- so this test exercises the actual generated request-body
// logic, not a hand-written reimplementation of it. Test-only, and (as with that
// precedent) no external or untrusted input is ever interpolated into the function
// body: the expression string is read from this repo's OWN build artifact
// (n8n/wf_enrichment_cloud.json), generated by this repo's own build script from this
// repo's own source (scripts/build_cloud_workflows.py) -- never from user input,
// network responses, or any other untrusted source.
import { test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const WF_PATH = path.join(ROOT, "n8n", "wf_enrichment_cloud.json");

function loadNode(name) {
  const wf = JSON.parse(fs.readFileSync(WF_PATH, "utf8"));
  const node = wf.nodes.find((n) => n.name === name);
  assert.ok(node, `${name} node present in built workflow`);
  return node;
}

// Strips the n8n "={{ <js expression> }}" wrapper and evaluates the inner expression
// with a mock $() node-accessor, mirroring how n8n itself evaluates it at runtime.
function evalExpr(rawExpr, identityKeys) {
  const m = /^=\{\{([\s\S]*)\}\}$/.exec(rawExpr.trim());
  assert.ok(m, `expression must be a single {{ }} n8n expression, got: ${rawExpr}`);
  const $ = (name) => {
    assert.equal(name, "Enrichment Gate", `unexpected $() call: ${name}`);
    return { item: { json: { identity_keys: identityKeys } } };
  };
  const fn = new Function("$", `"use strict"; return (${m[1]});`);
  return fn($);
}

function buildBody(identityKeys) {
  const node = loadNode("Lusha Enrich");
  const raw = evalExpr(node.parameters.jsonBody, identityKeys);
  return JSON.parse(raw);
}

const BANNED_ELEMENT_KEYS = [
  "firstName", "lastName", "companyName", "companyDomain", "domain", "phoneNumber", "jobTitle",
];

test("Lusha Enrich body: maps identity_keys -> {contacts:[{contactId, email, linkedinUrl}]}", () => {
  const body = buildBody({
    email: "brendan@lightningvisuals.com",
    linkedin_url: "https://linkedin.com/in/brendancarmody",
    firstName: "Brendan", lastName: "Carmody",
    companyName: "Lightning Visuals", domain: "lightningvisuals.com",
  });
  assert.deepEqual(Object.keys(body), ["contacts"]);
  assert.equal(body.contacts.length, 1);
  const c = body.contacts[0];
  assert.equal(c.contactId, "1");
  assert.equal(c.email, "brendan@lightningvisuals.com");
  assert.equal(c.linkedinUrl, "https://linkedin.com/in/brendancarmody");
  for (const banned of BANNED_ELEMENT_KEYS) {
    assert.ok(!(banned in body), `top-level body must not contain rejected property ${banned}`);
    assert.ok(!(banned in c), `contact element must not contain rejected property ${banned}`);
  }
});

test("Lusha Enrich body: omits linkedinUrl key when identity_keys.linkedin_url is blank", () => {
  const body = buildBody({ email: "a@b.com", linkedin_url: "" });
  assert.deepEqual(Object.keys(body.contacts[0]).sort(), ["contactId", "email"]);
});

test("Lusha Enrich body: omits email key when identity_keys.email is null, keeps linkedinUrl", () => {
  const body = buildBody({ email: null, linkedin_url: "https://linkedin.com/in/x" });
  assert.deepEqual(Object.keys(body.contacts[0]).sort(), ["contactId", "linkedinUrl"]);
});

test("Lusha Enrich body: neither email nor linkedin_url present -> empty contacts array (skip-not-retry, never a malformed element)", () => {
  const body = buildBody({ firstName: "X", lastName: "Y", companyName: "Z", domain: "z.com" });
  assert.deepEqual(body, { contacts: [] });
});

test("Lusha Enrich body: still reads identity by node name (Enrichment Gate), never bare $json", () => {
  const node = loadNode("Lusha Enrich");
  assert.ok(node.parameters.jsonBody.includes("$('Enrichment Gate').item.json.identity_keys"));
  assert.ok(!node.parameters.jsonBody.includes("$json.identity_keys"));
});
