// tests/n8n/mergeCompanyStaleTimestamp.test.mjs
//
// Phase 16.3 (companies twin of Phase 16.2 gpt #6) — compiled-node-body differential
// proving mergeCompanies.js's cacheKeys write moved from unconditional to promote-only,
// through the ACTUAL emitted `Merge Company` Code node jsCode (not the pure function in
// isolation). Reuses the tests/n8n/researchChainRowFlow.test.mjs `new Function(...)`
// execution mechanism over the repo's own committed/pinned jsCode — no external or
// untrusted input is ever interpolated into the function body.
//
// PRE body: tests/fixtures/merge_company_prefix_jscode.json — pinned from the committed
// n8n/wf_enrichment_cloud.json BEFORE the Phase 16.3 source edit landed. Write-once
// red-evidence artifact; never regenerated by any later phase.
// POST body: read LIVE out of the committed n8n/wf_enrichment_cloud.json, so the
// assertion tracks the shipped artifact, not a rebuilt-in-memory string.
//
// Pinning only the CLOUD variant: the `Merge Company` jsCode is character-identical
// across cloud and local_live (ENRICH_MERGE_CO bakes no config flags — no $vars/$env
// reads; see scripts/build_cloud_workflows.py's ENRICH_MERGE_CO definition), so one copy
// guards both.
import { test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");

const PRE_FIXTURE = JSON.parse(
  fs.readFileSync(path.join(ROOT, "tests/fixtures/merge_company_prefix_jscode.json"), "utf8")
).cloud["Merge Company"];

function loadPostBody() {
  const wf = JSON.parse(fs.readFileSync(path.join(ROOT, "n8n/wf_enrichment_cloud.json"), "utf8"));
  const node = wf.nodes.find((n) => n.name === "Merge Company");
  return node.parameters.jsCode;
}

// The compiled ENRICH_MERGE_CO wrapper only ever reads $input, but the harness passes
// the full researchChainRowFlow.test.mjs argument set for consistency with that mechanism.
function runMergeCompany(jsCode, row) {
  const $input = { all: () => [{ json: row }], get item() { return { json: row }; } };
  const $ = () => ({ all: () => [], get item() { return { json: undefined }; } });
  const $now = new Date();
  const fn = new Function("$", "$input", "$json", "$node", "$now", "$today",
    `"use strict";\n${jsCode}`);
  const out = fn($, $input, row, {}, $now, $now) || [];
  return (out[0] && out[0].json) || {};
}

// ~240 days before "now" (2026-07-28-ish) — obviously stale by CLAUDE.md §19.5's 180-day
// monthly-refresh TTL.
const STALE_VERIFIED_AT = "2025-12-01T00:00:00.000Z";
// From n8n/code/taxonomy.generated.js EVIDENCE_GATED_ORG_TYPES — an unevidenced claim to
// this value is withheld by mergeCompanies' own _needsEvidence gate (never promotable).
const GATED_ORG_TYPE = "governing_body_league";

function staleUnpromotedRow(evidenceUrl) {
  return {
    identity_keys: { domain: "exampleco.example" },
    existingRecord: {
      domain: "exampleco.example",
      name: "Example Co",
      lv_org_type: "other",
      lv_org_type_verified_at: STALE_VERIFIED_AT,
    },
    // Non-null so the node does not take its `merge: null` skip branch; empty so the
    // firmographic (waterfall) lane contributes nothing — only the research lane matters.
    scored: { best: {}, winners: {}, sourcesByField: {} },
    research_candidate: {
      matched: true,
      confidence: 90,
      data: { lv_org_type: GATED_ORG_TYPE },
      evidence_by_field: evidenceUrl ? { lv_org_type: evidenceUrl } : {},
    },
  };
}

test("vacuity guard: the compiled POST body produces a real merge with lv_org_type gated to needs_review and absent from canonicalPatch", () => {
  const out = runMergeCompany(loadPostBody(), staleUnpromotedRow());
  assert.ok(out.merge && typeof out.merge === "object", "merge is a real object, not the null skip branch");
  const d = out.merge.decisions.find((x) => x.field === "lv_org_type");
  assert.ok(d, "a decision entry exists for lv_org_type");
  assert.equal(d.decision, "needs_review", "unevidenced gated org_type is withheld by the evidence gate");
  assert.ok(!("lv_org_type" in out.merge.canonicalPatch), "lv_org_type never reached canonicalPatch");
});

test("RED: the PRE-fix compiled body stamps lv_org_type_verified_at on an unpromoted (needs_review) field — CLAUDE.md §19.5 consequence: this permanently suppresses the monthly stale-refresh scan for the record", () => {
  const out = runMergeCompany(PRE_FIXTURE, staleUnpromotedRow());
  const stamp = out.merge && out.merge.cacheKeys && out.merge.cacheKeys.lv_org_type_verified_at;
  assert.ok(stamp, "pre-fix body must emit a fresh lv_org_type_verified_at even though the field was withheld");
  assert.notEqual(stamp, STALE_VERIFIED_AT, "the pre-fix body actively refreshes the timestamp rather than leaving it stale");
});

test("GREEN: the POST-fix compiled body (shipped n8n/wf_enrichment_cloud.json) emits NO lv_org_type_verified_at for the same unpromoted row", () => {
  const out = runMergeCompany(loadPostBody(), staleUnpromotedRow());
  assert.ok(!(out.merge.cacheKeys && "lv_org_type_verified_at" in out.merge.cacheKeys),
    "an unpromoted field must not be marked fresh");
});

test("CONTROL (no over-fix): the same row WITH evidence still promotes and still stamps lv_org_type_verified_at on the POST body", () => {
  // evidence_by_field values appear in-repo as both a plain string URL and a {url} object;
  // mergeCompanies only `_isBlank`-checks the value, so either shape satisfies the gate —
  // this test uses a plain string URL.
  const out = runMergeCompany(loadPostBody(), staleUnpromotedRow("https://exampleco.example/about"));
  assert.equal(out.merge.canonicalPatch.lv_org_type, GATED_ORG_TYPE, "evidenced gated value promotes");
  assert.ok(out.merge.cacheKeys.lv_org_type_verified_at, "promoted field still stamps its cache key");
});
