// tests/n8n/researchRequestCountryRegionContract.test.mjs
//
// REQ-country-region-policy closure gap: the deployed research prompt schema only asked
// for 6 fields (lv_org_type/lv_produces_content/lv_content_type/lv_is_hardware_vendor/
// lv_is_gambling_operator/lv_sponsorship_reliant) — lv_country_region_normalized was
// structurally absent, so the research lane could never produce a candidate for the
// field-policy entry mergeCompanies.js already carries (min_confidence 75, Phase 21-04).
// Mirrors tests/n8n/researchRequestSponsorshipContract.test.mjs's proof shape exactly
// (COPY-01 precedent), for the 7th field.
//
// Executes the REAL committed Code node bodies via `new Function` — no external or
// untrusted input is ever interpolated into the function body; every string executed
// here is read from this repo's own build artifact, generated by this repo's own build
// script from this repo's own source.
import { test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const WF_CLOUD_PATH = path.join(ROOT, "n8n", "wf_enrichment_cloud.json");
const WF_LOCAL_LIVE_PATH = path.join(ROOT, "n8n", "wf_enrichment_local_live.json");

function loadNode(wfPath, name) {
  const wf = JSON.parse(fs.readFileSync(wfPath, "utf8"));
  const node = wf.nodes.find((n) => n.name === name);
  assert.ok(node, `${name} node present in ${wfPath}`);
  return node;
}

function runBuildResearchRequest(jsCode, row) {
  const $input = { all: () => [{ json: row }], get item() { return { json: row }; } };
  const $ = () => ({ all: () => [], get item() { return { json: undefined }; } });
  const $now = new Date("2026-07-30T00:00:00Z");
  const fn = new Function("$", "$input", "$json", "$node", "$now", "$today",
    `"use strict";\n${jsCode}`);
  const out = fn($, $input, row, {}, $now, $now) || [];
  return (out[0] && out[0].json) || {};
}

function runValidateResearchOutput(jsCode, preHttpRow, httpResponseItem) {
  const $ = (name) => {
    assert.equal(name, "Build Research Request", `unexpected $() call: ${name}`);
    return { all: () => [{ json: preHttpRow }], get item() { return { json: preHttpRow }; } };
  };
  const $input = { all: () => [{ json: httpResponseItem }], get item() { return { json: httpResponseItem }; } };
  const $now = new Date("2026-07-30T00:00:00Z");
  const fn = new Function("$", "$input", "$json", "$node", "$now", "$today",
    `"use strict";\n${jsCode}`);
  const out = fn($, $input, httpResponseItem, {}, $now, $now) || [];
  return (out[0] && out[0].json) || {};
}

const SEED_ROW = {
  research_needed: true,
  identity_keys: { domain: "exampleracing.example", companyName: "Example Racing League" },
  existingRecord: { domain: "exampleracing.example", name: "Example Racing League" },
};

function parsedRequiredFields(body) {
  const payload = JSON.parse(body.messages[0].content);
  return payload.required_fields;
}

test("(a) required_fields contains lv_country_region_normalized", () => {
  const node = loadNode(WF_CLOUD_PATH, "Build Research Request");
  const out = runBuildResearchRequest(node.parameters.jsCode, SEED_ROW);
  const fields = parsedRequiredFields(out.research_request_body);
  assert.ok(fields.includes("lv_country_region_normalized"),
    "REQ-country-region-policy: the research request must ask for lv_country_region_normalized");
});

test("(b) the forced JSON response schema declares lv_country_region_normalized inside the data shape", () => {
  const node = loadNode(WF_CLOUD_PATH, "Build Research Request");
  const out = runBuildResearchRequest(node.parameters.jsCode, SEED_ROW);
  const system = out.research_request_body.system;
  const schemaStart = system.indexOf('{"data":{');
  assert.ok(schemaStart !== -1, "forced JSON schema substring must be present in the prompt");
  const schemaEnd = system.indexOf('"evidence_by_field"', schemaStart);
  assert.ok(schemaEnd !== -1, "schema must be followed by evidence_by_field");
  const schemaSubstring = system.slice(schemaStart, schemaEnd);
  assert.ok(schemaSubstring.includes("lv_country_region_normalized"),
    "the region field must be declared INSIDE the forced response schema's data shape, not merely mentioned in prose");
});

test("(c) local_live variant's compiled Build Research Request body also requests the field (shared factory)", () => {
  const node = loadNode(WF_LOCAL_LIVE_PATH, "Build Research Request");
  assert.ok(node.parameters.jsCode.includes("lv_country_region_normalized"),
    "the local_live variant must carry the same fix as cloud (_enrich_build_research_request_js is shared)");
});

test("(d) CHAIN SURVIVAL: a valid enum region value survives Validate Research Output untouched", () => {
  const node = loadNode(WF_CLOUD_PATH, "Validate Research Output");
  const responseData = {
    lv_org_type: "governing_body_league",
    lv_content_type: ["live_broadcast"],
    lv_country_region_normalized: "AU",
  };
  const httpResponseItem = {
    id: "msg_1", type: "message", role: "assistant",
    content: [{ type: "text", text: JSON.stringify({ data: responseData, matched: true, confidence: 88 }) }],
    model: "claude", usage: {},
  };
  const preHttpRow = { existingRecord: { domain: "exampleracing.example" } };
  const out = runValidateResearchOutput(node.parameters.jsCode, preHttpRow, httpResponseItem);
  assert.equal(out.research_candidate.data.lv_country_region_normalized, "AU");
});

test("(e) GUARD: a hallucinated/garbage region value is clamped to 'Unknown', not passed through raw", () => {
  const node = loadNode(WF_CLOUD_PATH, "Validate Research Output");
  const responseData = {
    lv_org_type: "governing_body_league",
    lv_country_region_normalized: "Freedonia", // not in AU|NZ|ANZ|Other|Unknown
  };
  const httpResponseItem = {
    id: "msg_1", type: "message", role: "assistant",
    content: [{ type: "text", text: JSON.stringify({ data: responseData, matched: true, confidence: 88 }) }],
    model: "claude", usage: {},
  };
  const preHttpRow = { existingRecord: { domain: "exampleracing.example" } };
  const out = runValidateResearchOutput(node.parameters.jsCode, preHttpRow, httpResponseItem);
  assert.equal(out.research_candidate.data.lv_country_region_normalized, "Unknown");
});

test("(f) GUARD is a no-op for null/absent region (stays null, never coerced to 'Unknown')", () => {
  const node = loadNode(WF_CLOUD_PATH, "Validate Research Output");
  const responseData = { lv_org_type: "governing_body_league", lv_country_region_normalized: null };
  const httpResponseItem = {
    id: "msg_1", type: "message", role: "assistant",
    content: [{ type: "text", text: JSON.stringify({ data: responseData, matched: true, confidence: 88 }) }],
    model: "claude", usage: {},
  };
  const preHttpRow = { existingRecord: { domain: "exampleracing.example" } };
  const out = runValidateResearchOutput(node.parameters.jsCode, preHttpRow, httpResponseItem);
  assert.equal(out.research_candidate.data.lv_country_region_normalized, null,
    "an explicit null (model correctly declined to guess) must stay null, not become the literal string 'Unknown'");
});
