// tests/n8n/researchRequestSponsorshipContract.test.mjs
//
// GAP 1 (COPY-01, 18-VERIFICATION.md CR-01) — the shipped "Build Research Request" node
// body must actually ASK the model for lv_sponsorship_reliant (both in required_fields
// and in the forced JSON response schema), and that value must survive the frozen
// "Validate Research Output" node's wholesale `raw.data` spread into
// research_candidate.data. Plan 18-02 proved the copy step ONE node later (Merge
// Company, tests/n8n/sponsorshipReliantCopyLoop.test.mjs); this test proves the two
// nodes upstream of it.
//
// Executes the REAL committed Code node bodies via `new Function` — the same idiom
// tests/n8n/mergeCompanyStaleTimestamp.test.mjs / tests/n8n/researchChainRowFlow.test.mjs
// already use to run committed jsCode — so this test exercises the actual generated
// prompt/validation logic, not a hand-written reimplementation of it. No external or
// untrusted input is ever interpolated into the function body: every string executed
// here is read from this repo's OWN build artifact (n8n/wf_enrichment_cloud.json /
// n8n/wf_enrichment_local_live.json), generated by this repo's own build script from
// this repo's own source (scripts/build_cloud_workflows.py) — never from user input,
// network responses, or any other untrusted source.
//
// The CLOUD variant bakes ANTHROPIC_SONNET_MODEL/WEB_RESEARCH_MAX_SEARCHES as literals
// (_flag_const(..., cloud=True)), so it runs under `new Function` with no $env/$vars
// stub — used for the EXECUTED assertions (a)-(c),(e). The LOCAL_LIVE variant emits
// `($vars && $vars.X) || $env.X || <default>` and would need those stubs to execute; its
// parity is asserted by string containment on its compiled body instead (d).
import { test } from "node:test";
import assert from "node:assert/strict";
import { fileURLToPath } from "node:url";
import path from "node:path";
import fs from "node:fs";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..", "..");
const WF_CLOUD_PATH = path.join(ROOT, "n8n", "wf_enrichment_cloud.json");
const WF_LOCAL_LIVE_PATH = path.join(ROOT, "n8n", "wf_enrichment_local_live.json");

function loadNode(wfPath, name) {
  const wf = JSON.parse(fs.readFileSync(wfPath, "utf8"));
  const node = wf.nodes.find((n) => n.name === name);
  assert.ok(node, `${name} node present in ${wfPath}`);
  return node;
}

function runBuildResearchRequest(jsCode, row) {
  const $input = { all: () => [{ json: row }], get item() { return { json: row }; } };
  const $ = () => ({ all: () => [], get item() { return { json: undefined }; } });
  const $now = new Date("2026-07-29T00:00:00Z");
  const fn = new Function("$", "$input", "$json", "$node", "$now", "$today",
    `"use strict";\n${jsCode}`);
  const out = fn($, $input, row, {}, $now, $now) || [];
  return (out[0] && out[0].json) || {};
}

// "Validate Research Output" reads its row back by node name ($('Build Research
// Request')), never bare $json (the upstream HTTP node replaces $json with the API
// response) — mirrors tests/n8n/researchChainRowFlow.test.mjs's row-recovery mechanism.
function runValidateResearchOutput(jsCode, preHttpRow, httpResponseItem) {
  const $ = (name) => {
    assert.equal(name, "Build Research Request", `unexpected $() call: ${name}`);
    return { all: () => [{ json: preHttpRow }], get item() { return { json: preHttpRow }; } };
  };
  const $input = { all: () => [{ json: httpResponseItem }], get item() { return { json: httpResponseItem }; } };
  const $now = new Date("2026-07-29T00:00:00Z");
  const fn = new Function("$", "$input", "$json", "$node", "$now", "$today",
    `"use strict";\n${jsCode}`);
  const out = fn($, $input, httpResponseItem, {}, $now, $now) || [];
  return (out[0] && out[0].json) || {};
}

// research_needed:true + an identity_keys domain/companyName + an existingRecord —
// enough that the node does not take its `research_request_body: null` short-circuit.
const SEED_ROW = {
  research_needed: true,
  identity_keys: { domain: "exampleracing.example", companyName: "Example Racing League" },
  existingRecord: { domain: "exampleracing.example", name: "Example Racing League" },
};

function parsedRequiredFields(body) {
  const payload = JSON.parse(body.messages[0].content);
  return payload.required_fields;
}

test("(a) VACUITY GUARD: the executed cloud Build Research Request body returns a real request whose required_fields already contains the control field", () => {
  const node = loadNode(WF_CLOUD_PATH, "Build Research Request");
  const out = runBuildResearchRequest(node.parameters.jsCode, SEED_ROW);
  assert.ok(out.research_request_body, "research_needed:true must not take the null short-circuit");
  const fields = parsedRequiredFields(out.research_request_body);
  assert.ok(fields.includes("lv_content_type"), "control field (lv_content_type) must already be requested");
});

test("(b) GREEN (RED until the fix lands): required_fields contains lv_sponsorship_reliant", () => {
  const node = loadNode(WF_CLOUD_PATH, "Build Research Request");
  const out = runBuildResearchRequest(node.parameters.jsCode, SEED_ROW);
  const fields = parsedRequiredFields(out.research_request_body);
  assert.ok(fields.includes("lv_sponsorship_reliant"),
    "COPY-01/CR-01: the research request must ask for lv_sponsorship_reliant");
});

test("(c) GREEN (RED until the fix lands): the forced JSON response schema declares lv_sponsorship_reliant inside the data shape", () => {
  const node = loadNode(WF_CLOUD_PATH, "Build Research Request");
  const out = runBuildResearchRequest(node.parameters.jsCode, SEED_ROW);
  const system = out.research_request_body.system;
  const schemaStart = system.indexOf('{"data":{');
  assert.ok(schemaStart !== -1, "forced JSON schema substring must be present in the prompt");
  // The next top-level schema key after `data` is `evidence_by_field` — slicing up to it
  // isolates exactly the `data` object's declared shape, so a passing mention elsewhere
  // in the prompt's prose cannot satisfy this assertion.
  const schemaEnd = system.indexOf('"evidence_by_field"', schemaStart);
  assert.ok(schemaEnd !== -1, "schema must be followed by evidence_by_field");
  const schemaSubstring = system.slice(schemaStart, schemaEnd);
  assert.ok(schemaSubstring.includes("lv_sponsorship_reliant"),
    "the sponsorship field must be declared INSIDE the forced response schema's data shape, not merely mentioned in prose");
});

test("(d) GREEN (RED until the fix lands): the local_live variant's compiled Build Research Request body also requests the field (both variants share one factory)", () => {
  const node = loadNode(WF_LOCAL_LIVE_PATH, "Build Research Request");
  assert.ok(node.parameters.jsCode.includes("lv_sponsorship_reliant"),
    "the local_live variant must carry the same fix as cloud (_enrich_build_research_request_js is shared)");
});

test("(e) CHAIN SURVIVAL: a research response carrying lv_sponsorship_reliant survives Validate Research Output into research_candidate.data untouched", () => {
  const node = loadNode(WF_CLOUD_PATH, "Validate Research Output");
  const responseData = {
    lv_org_type: "governing_body_league",
    lv_content_type: ["live_broadcast"], // control field, asserted alongside
    lv_sponsorship_reliant: true,
  };
  const httpResponseItem = {
    id: "msg_1", type: "message", role: "assistant",
    content: [{ type: "text", text: JSON.stringify({ data: responseData, matched: true, confidence: 88 }) }],
    model: "claude", usage: {},
  };
  const preHttpRow = { existingRecord: { domain: "exampleracing.example" } };
  const out = runValidateResearchOutput(node.parameters.jsCode, preHttpRow, httpResponseItem);
  assert.ok(out.research_candidate, "Validate Research Output produced a research_candidate");
  assert.deepEqual(out.research_candidate.data.lv_content_type, ["live_broadcast"],
    "control field must survive the frozen validator's spread untouched");
  assert.equal(out.research_candidate.data.lv_sponsorship_reliant, true,
    "the frozen webResearch.js wholesale `{...raw.data}` spread must pass an unlisted field through untouched — this passes pre-fix too, as a permanent regression guard on that spread semantic");
});
